[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = { workspace = true }
log = { workspace = true }
tracel-xtask-commands = { path = "../crates/tracel-xtask-commands" }
tracel-xtask-macros = { path = "../crates/tracel-xtask-macros" }