[package]
name = "xtask"
version = "1.0.1"
edition = "2021"

[dependencies]
strum = { workspace = true }
log = { workspace = true }
tracel-xtask = { path = "../crates/tracel-xtask" }

[dev-dependencies]
rstest = { workspace = true }
