[package]
name = "tracel-xtask"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
derive_more = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
tracing-subscriber = { workspace = true }
tracel-xtask-macros = { path = "../tracel-xtask-macros", version = "0.1.0" }

[dev-dependencies]
rstest = { workspace = true }